/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package virtual.pets.amok;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        PetDriver petDriver = new PetDriver();
        petDriver.driver();
    }
}
